### ISSUE TITLE
Upstream deps sync

### ISSUE THREAD

**Issue by codechips** [coc-extensions/coc-svelte#16]
I was having trouble with Typescript and noticed that dependencies are way behind Svelte's lang server. Problem went away after I updated them to latest and greatest. 

I now maintain my own fork of the plugin, but what thinking if this can somehow be automated to keep upstream deps in sync?

**Comment by Jayphen** [comment]
Can you please share your fork?

**Comment by codechips** [comment]
https://github.com/codechips/coc-svelte

**Comment by davidroeca** [comment]
Apologies for the delay here - it's been a while since I've coded in svelte, but now that I'm working on a project that uses it, I've also noticed that these tools are quite out of date. I'll start watching this repo, so that I don't miss these issues in the future. The latest lang server is supported on https://github.com/davidroeca/coc-svelte/tree/resync-language-tools until https://github.com/coc-extensions/coc-svelte/pull/17 gets merged

**Comment by codechips** [comment]
All right. Thanks. Closing this then.
